name: Build on MacOS with make
on: [pull_request, workflow_dispatch]

jobs:
  build:
    name: build
    runs-on: macos-12
    steps:
      - name: Install dependencies
        run: |
          brew install make autoconf curl json-c gettext

      - name: Clone postgres repository
        uses: actions/checkout@v4
        with:
          repository: 'postgres/postgres'
          ref: 'a81e5516fa4bc53e332cb35eefe231147c0e1749'
          path: 'src'

      - name: Clone postgres-tde-ext repository
        uses: actions/checkout@v2
        with:
          path: 'src/contrib/postgres-tde-ext'

      - name: Create pgsql dir
        run: mkdir -p /opt/pgsql

      - name: Build postgres
        run: |
          ./configure --with-openssl  --enable-tap-tests=no --prefix=/opt/pg
          make -j
          sudo make install
        working-directory: src

      - name: Build postgres-tde-ext
        run: |
          ./configureq
          make -j
          sudo make install
        working-directory: src/contrib/postgres-tde-ext

      - name: Run debug commands on failure
        if: ${{ failure() }}
        run: |
          env
          go version
          go env
          pwd
          git status


